### ISSUE TITLE
chained_scbs not full framerate

### ISSUE THREAD

**Issue by newsie-oss** [libretro/libretro-handy#71]
Real hardware runs this demo at fluid 60 fps.
https://github.com/42Bastian/lynx_hacking/tree/master/chained_scbs

With latest commit, it runs much slower. Ms. Pac-Man is also noticeably lagging behind real hardware now (when lots of dots on-screen).

Beetle-Lynx does not have these problems.

**Comment by twinaphex** [comment]
Are you referring to this PR being merged?

https://github.com/libretro/libretro-handy/pull/70

The author found that this made Ms. Pac-Man very slow on a PSP.

**Comment by fjtrujy** [comment]
Hello @newsie-oss,
I think that the issue must be in a different place. You said that `Beetle-Lynx` doesn't have this issue, however, the same lines that they were changed today are present in the `/beetle-lynx-libretro` as you can see here

https://github.com/libretro/beetle-lynx-libretro/blob/74dde204c0ec6c4bc4cd7821c14548387fbd9ce8/mednafen/lynx/susie.cpp#L855

https://github.com/libretro/beetle-lynx-libretro/blob/74dde204c0ec6c4bc4cd7821c14548387fbd9ce8/mednafen/lynx/susie.cpp#L900

Do you have any clue?

Thanks

**Comment by tailshine** [comment]
https://github.com/libretro/libretro-handy/pull/72
- chained_scbs will run now.
- Ms. Pac-Man is better. I'm not totally sure that is correct; it seems slow to me still, even with beetle_lynx. After 10-20 pellets are eaten, the game picks up to normal speed. But I haven't touched this game in real hardware for awhile and would need to ask AtariAge for opinion.

**Comment by tailshine** [comment]
Found a real video. Ms. Pac-Man runs smooth there. Eh.
https://www.youtube.com/watch?v=WdTboU1F5rM

**Comment by trioan** [comment]
Part of the problem is that real hardware packs 2 pixels into 1 byte. So that's 1 RAM read-modify-write penalty, whereas Handy treats it as two separate memory accesses.

Beetle-Lynx-Libretro always uses 4 cpu cycles instead of the normal 5 which is used in handy and real hardware. But real hw can also use 4 *if* rom / ram is within same 256-byte page, which could be often but not reliable. This might be an interesting idea though or add as a compile-time flag.

I would have to check the mikie irq wakeup patch though, to see what affect it would have.

**Comment by newsie-oss** [comment]
Thanks, your PR works for both!
